#!/usr/bin/env bash

printf "[\e[0;34mNOTICE\e[0m] Setting up environment for terraform.\n"
mkdir -p ~/.aws ~/.ssh
if [[ -f /.dockerenv ]]; then
  echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
fi

cat <<EOF > ~/.aws/credentials
[$AWS_USER_NAME]
aws_access_key_id=$AWS_ACCESS_KEY_ID
aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
EOF

cat <<EOF > ~/.aws/config
[default]
role_arn = $AWS_ROLE_ARN
source_profile = $AWS_USER_NAME
output = $AWS_DEFAULT_OUTPUT
region = $AWS_DEFAULT_REGION

[profile $AWS_USER_NAME]
output = $AWS_DEFAULT_OUTPUT
region = $AWS_DEFAULT_REGION
EOF
